
allprojects {

    repositories {
        maven { url = 'https://repo1.maven.org/maven2/' } // miroir alternatif
        mavenCentral()
    }

    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    languageVersion = JavaLanguageVersion.of(24)
    options.fork = true
    options.forkOptions.jvmArgs = ['-Xmx1g']
}


subprojects {
    apply plugin: 'java'

    dependencies {

        implementation 'org.apache.logging.log4j:log4j-api:2.24.1'
        implementation 'org.apache.logging.log4j:log4j-core:2.24.1'
        implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.24.1'

        implementation 'org.springframework:spring-context:7.0.7'
        implementation 'com.google.code.gson:gson:2.3.1'

        implementation 'org.springframework:spring-aop:5.3.1'
        implementation 'org.aspectj:aspectjrt:1.9.6'
        implementation 'org.aspectj:aspectjweaver:1.9.6'
        implementation 'org.projectlombok:lombok:1.18.30'

        implementation 'org.springframework:spring-orm:6.2.9'
        implementation 'org.hibernate.orm:hibernate-core:6.6.2.Final'
        implementation 'com.h2database:h2:2.3.232' // base embarquée pour l'exemple
        implementation 'com.zaxxer:HikariCP:5.1.0' // pool de connexions

    }
    test {
        useJUnitPlatform()
    }
}